### PR TITLE
Transport params

### PR DESCRIPTION
**Pull request by GrumpyOldTroll**

### CODE REVIEW

**Comment by Karthikdasari0423** [comment]
Hai @GrumpyOldTroll @MaxF12 

root@ubuntu:/tmp# python3 /tmp/aioquic-main_mc/aioquic-main/examples/http3_server.py --certificate /tmp/aioquic-main_mc/aioquic-main/tests/ssl_cert.pem --private-key /tmp/aioquic-main_mc/aioquic-main/tests/ssl_key.pem -v
Traceback (most recent call last):
  File "/tmp/aioquic-main_mc/aioquic-main/examples/http3_server.py", line 14, in <module>
    from aioquic.asyncio import QuicConnectionProtocol, serve
  File "/usr/local/lib/python3.8/dist-packages/aioquic/asyncio/__init__.py", line 1, in <module>
    from .client import connect  # noqa
  File "/usr/local/lib/python3.8/dist-packages/aioquic/asyncio/client.py", line 8, in <module>
    from ..quic.connection import QuicConnection
  File "/usr/local/lib/python3.8/dist-packages/aioquic/quic/connection.py", line 56, in <module>
    from ..multicast import do_join
  File "/usr/local/lib/python3.8/dist-packages/aioquic/multicast.py", line 1, in <module>
    import multicast_glue
ModuleNotFoundError: No module named 'multicast_glue'

am i missing anything here

Thank you.

**Comment by GrumpyOldTroll** [comment]
Sorry about this PR, it was intended to go into https://github.com/MaxF12/aioquic and not here, I closed it as soon as I realized my mistake.  We're using that fork to experiment with [draft-jholland-quic-multicast](https://github.com/GrumpyOldTroll/draft-jholland-quic-multicast), but it's still far from ready, and I clicked the wrong thing when trying to add to that fork.

If you're interested in working on that one, you'd need to install [libmcrx](https://github.com/GrumpyOldTroll/libmcrx) and do the "pip install -e .", with the instructions that are so far only in the MacOS section of the [README](https://github.com/MaxF12/aioquic/blob/main/README.rst#os-x).

But if you're trying to sanity-check this PR for the upstream project, please disregard. That was a mistaken PR, and sorry to have troubled you.  Maybe at some point when we think it appropriate we'll look to merge the extension, but not this month.

**Comment by Karthikdasari0423** [comment]
Thank you for replying back.

First i tried to raise an issue with the  https://github.com/MaxF12/aioquic but as a fork i was unable to do .

Could you please confirm if i install libmcrx ,then would the mc_server.py & mc_client.py work on Ubuntu machine?

Thank you

**Comment by GrumpyOldTroll** [comment]
I hadn't yet tried it on ubuntu, but I just went ahead on 20.04 and it ultimately worked for me.  But while trying to get it running I hit a few problems whose solutions aren't yet documented:

1. had to set LD_LIBRARY_PATH in order to load my sandboxed libmcrx build
2. had a dependency problem with werkzeug and flask and httpbin
3. wheel wasn't there by default, which gave some errors

So my full process to bring it up I think would be matched by this sequence:

~~~
sudo apt install libssl-dev python3-dev
LOCALD=${HOME}/sandbox/local
mkdir -p ${LOCALD}
cd ${HOME}/sandbox
git clone https://github.com/GrumpyOldTroll/libmcrx
cd libmcrx
./autogen.sh
./configure --prefix=${LOCALD}
make && make install
cd ..
python3 -m venv qmc
source qmc/bin/activate
git clone https://github.com/MaxF12/aioquic
cd aioquic
pip install wheel asgiref dnslib httpbin starlette "flask<2.1" "werkzeug<2.1" wsproto
export CFLAGS="-I/usr/local/opt/openssl/include -I${LOCALD}/include"
export LDFLAGS="-L/usr/local/opt/openssl/lib -L${LIBMCRXD}/lib"
pip install -e .
~~~

After this, I think it works for me to go into ${HOME}/sandbox/aioquic in 2 different terminals and run:

~~~
export LD_LIBRARY_PATH=${HOME}/sandbox/local/lib
source ${HOME}/sandbox/qmc/bin/activate
~~~

Then examples/mc_server.py and examples/mc_client.py can be run in those 2 separate terminals and successfully make a connection:

~~~
python examples/mc_server.py --certificate tests/ssl_cert.pem --private-key tests/ssl_key.pem
python examples/mc_client.py --ca-certs tests/pycacert.pem --remote-port 4433 --server localhost
~~~

(Note that this does not yet have multicast running to do the transport, it just gets to the point you can have it running at all, so you can hack on it usefully.)

HTH.

**Comment by Karthikdasari0423** [comment]
Thank you for replying back.

Thank you for providing info how to work with mc_server and mc_client.py.

Will try in my machine.

**Comment by GrumpyOldTroll** [comment]
Also, issues have now been enabled on https://github.com/MaxF12/aioquic, that's probably a better place to open the next one.  Thanks for asking about it.

**Comment by Karthikdasari0423** [comment]
Thank you for enabling issues in  https://github.com/MaxF12/aioquic.

**Pull request closed without merging**
