### PR TITLE
add a protocol and is_closing to fix drain on writers

### PR DESCRIPTION
**Pull request by jmgurney**
This fixes issue #250 

This fix can be demonstrated by the tests that will be shortly committed to ntunnel: https://www.funkthat.com/gitea/jmg/ntunnel .

### CODE REVIEW

**Review by ahopkins — APPROVED** [review]

**Comment by jlaine** [comment]
The docs error is not your fault, it should be fixed by rebasing on top of main.

The drop in coverage on the other hand is yours to fix :)

**Comment by jlaine** [comment]
Hi! Any chance of fixing the missing test coverage please?

**Comment by jlaine** [comment]
Hello, do you still plan to add the missing tests?

**Comment by jlaine** [comment]
Closing in favour of #477

**Pull request closed without merging**
