### PR TITLE
Change DataGram size to allowed Limit

### PR DESCRIPTION
**Pull request by Arvind2222**
* 1280 to 1200 Ref #https://www.rfc-editor.org/rfc/rfc9000.html#name-datagram-size

### CODE REVIEW

**Comment by Arvind2222** [comment]
@jlaine Could you please review

**Comment by jlaine** [comment]
Since we've been bitten by the distinction between payload size and IP packet size, a comment seems necessary here.

**Comment by jlaine** [comment]
As expected this breaks test pretty much all over the place, they need fixing..

**Comment by jlaine** [comment]
Let's address this in #400

**Pull request closed without merging**
