### PR TITLE
[webtransport] update H3_DATAGRAM value

### PR DESCRIPTION
**Pull request by saitolume**
Update H3_DATAGRAM according to the latest specs.

ref: https://datatracker.ietf.org/doc/html/draft-ietf-masque-h3-datagram#:~:text=H3_DATAGRAM%20%20%7C%200xffd277%20%7C%20This%20Document%20%7C%200

### CODE REVIEW

**Comment by jlaine** [comment]
Is this change of constants the *only* required change?

**Comment by jlaine** [comment]
Also could you please fix the linter error by making the hex value uppercase?

**Comment by saitolume** [comment]
> Is this change of constants the only required change?

Yes, I have confirmed that the [sample](https://github.com/GoogleChrome/samples/tree/gh-pages/webtransport) works correctly.

**Comment by saitolume** [comment]
> Also could you please fix the linter error by making the hex value uppercase?

@jlaine  Fixed it! Please check again.

**Comment by jlaine** [comment]
Hm. I'm not convinced that's the only required change (the datagram framing is not what I recall), but let's go.

**Comment by yutakahirano** [comment]
Just FYI, we have some logic in our server to offset the version difference (see [H3ConnectionWithDatagram04](https://github.com/web-platform-tests/wpt/blob/master/tools/webtransport/h3/webtransport_h3_server.py#L39) and `supports_h3_datagram_04` calls in https://github.com/web-platform-tests/wpt/blob/master/tools/webtransport/h3/webtransport_h3_server.py).

**Pull request merged**
