### PR TITLE
Initial attempt at a DNS over QUIC client/server

### PR DESCRIPTION
**Pull request by tigertoes**
One thing to note about this pull request is that it depends on dnslib, which has *not* been included into `requirements/doc.txt` as this is an example piece of code. I'm happy to consider an alternative (including spinning it off into another repository) if this isn't the right thing to do.

### CODE REVIEW

**Comment by jlaine** [comment]
Welcome back @tigertoes, thank you for this cool stuff!

One question comes to mind: on the server side, the request to the upstream resolver seems to be synchronous, is that right?

**Comment by tigertoes** [comment]
You're right, it's a blocking and only done to get something working, it's not necessarily the right answer. Happy to change it if you think it's more appropriate.

**Comment by jlaine** [comment]
There is an async DNS package here: https://github.com/saghul/aiodns

Does it cover your needs? Failing that we could probably just run the lookup code in an executor.

**Comment by jlaine** [comment]
On the server side, as your code is nicely structured I'm pondering merging it straight into the HTTP/3 server example, that way we could have a public-facing server at quic.aiortc.org

**Comment by tigertoes** [comment]
I'm not sure merging it into the HTTP/3 server is the right call - DoQ aims to have not only a separate ALPN, but run on a completely different port. Unless of course, you were intending the HTTP/3 example server to listen on both 443 and 874?

I'll take a look at making the upstream resolution happen asynchronously.

**Comment by jlaine** [comment]
Ah I hadn't realised it's supposed to run on a separate port! Let's keep things separate in that case.

**Pull request merged**
