### PR TITLE
updated help for "--retry" argument in examples/http3_server.py

### PR DESCRIPTION
**Pull request by Karthikdasari0423**
just changed help comment from "send a retry for new connections" to "the ASGI application as : to send a retry for new connections" for "--retry" argument

### CODE REVIEW

**Comment by jlaine** [comment]
I don't understand the new comment, how is --retry related to the ASGI app?

**Comment by Karthikdasari0423** [comment]
i mean to say "--retry" will accept the ASGI application right instead of any port number or ip address

**Comment by jlaine** [comment]
The `--retry` takes no arguments at all, it's just a flag which makes the server sent a RETRY to any new connection.

**Comment by Karthikdasari0423** [comment]
oh okay

Thank you for confirming and i tried with --retry demo:app and it worked,so i thought to  update "--retry" argument help.

**Pull request closed without merging**
