### PR TITLE
docs(readme): HTTP/3 is standardized now

### PR DESCRIPTION
**Pull request by max-wittig**
https://datatracker.ietf.org/doc/html/rfc9114

Since June 6th 2022

### CODE REVIEW

**Comment by jlaine** [comment]
The two parts of the sentence seem a bit weird, what do you think of:

`QUIC was standardised in RFC 9000 and HTTP/3  in RFC 9114.`

**Comment by ahopkins** [comment]
Would be nice to hyperlink the RFCs too.

**Comment by jlaine** [comment]
I've updated the PR to include links to the appropriate RFCs. I've also updated the IETF links in the code comments.

Let's see what CI has to say.

**Comment by max-wittig** [comment]
@jlaine Thanks for the changes!

**Pull request merged**
